import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
    const [width, setWidth] = useState(0)
    const [height, setHeight] = useState(0)
    const TITLE = 'AWS Services'
    const AUTHOR = 'Omar Assem'
    const AUTHOR_CONTACT = 'https://github.com/ocama'
    const MIND_MAP_URL = 'https://www.mindmeister.com/maps/public_map_shell/2644096869/servi-os-aws?width=600&height=400&z=auto&t=Xn2IalPKu3&no_share=1&no_logo=1'

    useEffect(() => {
        setWidth(window.innerWidth)
        setHeight(window.innerHeight)
    }, [])
    
    return (
        <>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>{TITLE} - Mind Map</h1>
                <h2 style={{marginBottom: 10}} >
                    Created by:
                    <a 
                        style={{marginLeft: 10, color: 'cyan'}}
                        href={AUTHOR_CONTACT} 
                        target='_blank'
                    >
                        {AUTHOR}
                    </a>
                </h2>
                <iframe width={width} height={height} src={MIND_MAP_URL} />
            </main>
        </>
    )
}
