import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { CONTENTS } from '@/utils/constants'
import CardContent from '@/components/CardContent'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mind Map Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            src="/mind-map-wiki-logo.svg"
            alt="Next.js Logo"
            width={700}
            height={400}
            priority
          />
        </div>
        <div className={styles.grid}>
          {CONTENTS.map((content, index) => (
            <CardContent
              key={index}
              title={content.title}
              description={content.description}
              url={content.url}
            />
          ))}
        </div>
      </main>
    </>
  )
}
