import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mind Map Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            src="/mind-map-wiki-logo.svg"
            alt="Next.js Logo"
            width={700}
            height={400}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://github.com/oismaelash/mindmap-wiki-nextjs-ts-frontend"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Open Source for All
            </p>
          </a>

          <a
            href="https://cloud.mindmap.wiki/aws-services"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              AWS Services <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Mind map here
            </p>
          </a>

          <a
            href="https://cloud.mindmap.wiki/cloud-services"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Cloud Services <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Mind map here
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
